### ISSUE TITLE
[Bug] SwiftMongoDB doesn't connect on iOS device

### ISSUE THREAD

**Issue by ghost** [Danappelxx/SwiftMongoDB#6] opened 2015-10-31 08:35 UTC
Ok, i got a couple question. Im still a beginner in mobile development. When i run my simulator in Xcode it pushes my data to my database fine with SwiftMongoDB but when i run it in my actual iPhone 6 it gives me an error that it can't connect. Is there something i have to do before i run it on my iPhone? And is anyone else getting multiple data saved to there Database? I even used the example project that was created by the SwiftMongoDB owner and it still copies whatever data i push to my database again when i run the simulator. I created a long function to kinda fix it, just wondering if it should be copying the data again every time i run my simulator...

**Comment by Danappelxx** [comment] 2015-10-31 09:12
I'll check out the issue with it not connecting on iPhone. Could you paste the exact error you're getting? Thanks. Also, to answer your question regarding multiple database inserts - the behavior is intentional. Every time you run an insert command in a collection, the document gets inserted rather than overwriting an existing, matching document (unless you provide an _id). This happens in other clients as well (ex: javascript).

**Comment by ghost** [comment] 2015-10-31 09:17
All its leaving in the console is "connection failed" when i run it on iPhone and its not updating my database at all but when i run it on Xcode simulator it does insert data in the database and the connection is fine. And i figured it was something like that, i just created a if conditional and fixed the repeating insert.

**Comment by Danappelxx** [comment] 2015-11-05 03:55
Hi! I'm not convinced that this is SwiftMongoDB's fault - first lets check if your network works at all. Try this code, for example:

``` swift
let url = NSURL(string: "http://httpbin.org/get")
let task = NSURLSession.sharedSession().dataTaskWithURL(url!) {(data, response, error) in
    if let error = error {
        print("Error: \(error)")
    } else {
        print(String.init(data: data!, encoding: NSUTF8StringEncoding)!)
    }
}
task.resume()
```

Sorry for the long response time.

**Comment by ghost** [comment] 2015-11-06 04:40
Thanks for replying,  I tried that piece of code that you sent and it does pull api data from a different source such as Reddit.com to my phone. But when i try from my actual MondoDB database still the same "connection failed". It still does work from the simulator but not my actual device. After doing some research online it seems like its something to do with the Plist after the update to Swift 2.0. I still can't figure it out though, its really beginning to bother me, i also know its going to be the smallest thing somewhere in the setting thats not letting me connect. Still though i can pull API data from other sources to my device "iPhone 6s" but not mongoDB, pretty strange.

**Comment by Danappelxx** [comment] 2015-11-06 04:45
Hi! This is strange and I'm not sure what could be causing it, I'll look into it. I just made some changes to how the underlying MongoDB driver is packaged, along with other minor modifications. Could you try updating SwiftMongoDB to the latest version? Make sure your Cartfile looks like this (note the `master`):

```
github "Danappelxx/SwiftMongoDB" "master"
```

and then run

``` shell
$ carthage update
```

There should be quite a lot of warnings but no errors. This does mean that you have to add the mongoc and bson frameworks to the project, though.

By the way, I created a [gitter](https://gitter.im/Danappelxx/SwiftMongoDB) earlier today - keep me updated on your progress there!

**Comment by Danappelxx** [comment] 2015-11-15 01:58
I think this issue was resolved in a discussion over at gitter. @Saulc009 was connecting to `localhost` on his iOS device, which was the cause of his issue.

**Closed as completed by Danappelxx** 2015-11-15 01:58 UTC
Labels: bug
